<a href="https://colab.research.google.com/github/nikhithapinto/AI-based-mediscope-recommendation-system/blob/main/Copy_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.0.2


In [3]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [11]:
arr=np.array([list1])
print(arr)

[[1 2 3]]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
list1=[1,2,3]
list2=[4,5,6]
arr1=np.array(list1)
arr2=np.array(list2)
print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


In [24]:
list1=[1,2,3]
list2=[4,5,6]
arr3=np.array([list1,list2])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [23]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr4=np.array([[list1,list2,list3]])
print(arr4)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [26]:
print(arr4.ndim)
print(arr3.ndim)

3
2


In [28]:
list1=[1,2,3]
list2=[4,5.0,6]
list3=[7,8,9]
arr4=np.array([[list1,list2,list3]])
print("shape",arr4.shape)
print("size",arr4.size)
print("type",arr4.dtype)
print("itemsize",arr4.itemsize)
print("ndim",arr4.ndim)

shape (1, 3, 3)
size 9
type float64
itemsize 8
ndim 3


In [42]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [46]:
a=np.zeros_like((2,3))
print(a)

[0 0]


In [33]:
a=np.full_like((2,3),3)
print(a)

[3 3]


In [41]:
a=np.full((2,3),3)
print(a)

[[3 3 3]
 [3 3 3]]


In [39]:
a=np.ones_like((2,3))
print(a)

[1 1]


In [40]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
a=np.empty(3)
print(a)

[4.9e-324 9.9e-324 1.5e-323]


In [32]:
a=np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [51]:
print(np.arange(2,20,2))

[ 2  4  6  8 10 12 14 16 18]


In [52]:
print(np.linspace(1,10,3))

[ 1.   5.5 10. ]


In [58]:
a=np.random.randint(2,10,(2,2))
print(a)

[[3 7]
 [9 9]]


In [75]:
ae=np.array([1,2,3,4,5,6,7,8,9])
print(ae[-6: :2])
print(ae[1:])
print(ae[1])

[4 6 8]
[2 3 4 5 6 7 8 9]
2


In [90]:
a=np.array([[1,2,3],[4,5,6]])
print(a[1:])
print(a[1])
print(a[:, 0])       # First column of an array
print(a[:, 1])       # Second column of an array
print(a[1:0,2])

[[4 5 6]]
[4 5 6]
[1 4]
[2 5]
[]


In [101]:
arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr3)
print(arr3[3::,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[]


In [114]:
a = np.array([[1,1],
             [1,1]])
b = np.array([[1,2,3],
            [4,5,6]])
# print(a)
# print(b)
c=np.dot(a,b)
print(c)

[[5 7 9]
 [5 7 9]]


In [116]:
arr = np.array([1,0,0,8])
print(arr)
np.save('my_array.npy', arr)

[1 0 0 8]
